spring:
  application:
    name: test-task
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgre}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        ddl-auto: validate
        default_schema: public

  flyway:
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgre}
    schemas: ${SCHEMA:public}
    baseline-on-migrate: true
    validate-migration-naming: true
    locations: db.migration

